### Crear un nuevo usuario
POST https://asistencia-backend-crtm.onrender.com/api/auth/register
Content-Type: application/json

{
    "username": "tecnico-demo",
    "password": "demo",
    "role": "Tecnico"
}


### Iniciar sesión con el nuevo usuario
POST https://asistencia-backend-crtm.onrender.com/api/auth/login
Content-Type: application/json

{
    "username": "tecnico-demo",
    "password": "demo"
}