### 1. Registrar un nuevo usuario (User Registration)
# @name registerUser
POST https://asistencia-backend-crtm.onrender.com/api/auth/register
Content-Type: application/json

{
    "username": "tecnico-test",
    "password": "simplepassword",
    "role": "Tecnico"
}

---

### 2. Iniciar sesión (Login)
# @name loginUser
POST https://asistencia-backend-crtm.onrender.com/api/auth/login
Content-Type: application/json

{
    "username": "tecnico-test",
    "password": "simplepassword"
}